### ISSUE TITLE
源站网址变更，不能显示结果，

### ISSUE THREAD

**Issue by GDZmax** [xiandanin/magnetW#101]
>操作系统版本：  
>应用版本：  

#### 问题描述：
源站网址变更，
BTSOW变更https://btsow.cyou/search/%E7%B4%97%E5%80%89%E3%81%BE%E3%81%AA%20%E7%84%A1%E7%A2%BC
BT蚂蚁变更
BTDB变更
BT目录变更https://91bt.info/
磁力宝变更http://cilibao.me/s/%e7%be%8e%e5%9b%bd%e9%98%9f%e9%95%bf_time_1.html?from=mw
BThub变更https://bthub.site/cn
磁力蜘蛛变更http://www.eclzz.net/s/%e7%be%8e%e5%9b%bd%e9%98%9f%e9%95%bf_rel_1.html?from=mw
磁力狗变更
磁力吧变更http://www.ciliba.life/s/%E7%BE%8E%E5%9B%BD%E9%98%9F%E9%95%BF/1/1.html?from=mw
btfox变更
sobt网址变更

不能显示结果，
zooqle
kickass torrents
动漫花园
thepiratebay.org

#### 异常日志（上传文件到这里）：
```

```

**Comment by xiandanin** [comment]
规则已更新，重启应用或者手动点击刷新，就可启用新的规则
