### ISSUE TITLE
希望继续更新网页版

### ISSUE THREAD

**Issue by xianrenba** [xiandanin/magnetW#53]
希望继续更新网页版，这个3.0的本地化版有点鸡肋。因为现在大家搜索磁力为了寻求方便，大多都是通过网页搞的，很少人会在本地安装一个客户端，本身太明显了，用这玩意的，大多是看片的，在电脑装个客户端，这样就尴尬了。

其次，一大堆目标源都需要翻墙才能搜索到，网页版的话，如果在国外服务器上，可以外代一些被墙渠道，但是在本地，这就尴尬了！~

刚体验了一下，客户端版本的，搜索太慢了，体验也很不好，比网页版差太多了，也不方便，因此，希望还是专注于网页版的开发。

**Comment by xiandanin** [comment]
其实客户端的目的也是为了脱离服务器
因为对于没有服务器的，用Tomcat去启动网页版反而没有客户端方便，客户端能跟系统更好协作
而对于有服务器的，因为网页版又是在公网上公开的，很容易惹上不必要的麻烦，从Demo域名被墙就能看出

**Comment by xiandanin** [comment]
这个issue我会置顶，大家可以用👍和 👎表态是否还需要网页，有什么建议也可以提

**Comment by StrollStars** [comment]
刚想来反馈下网页版不能用了，结果发现了有更新。
本来想说希望开发者能够保持网页版的更新，然后一用Win版之后我倒是希望开发者能够优先开发网页版了，理由如下：
①现在用这种架构开发的应用也不少，但是感觉这种架构不是Win的原生应用程序，更像是套了个浏览器Chrome的外壳，那还不如用网页版。
②Win版好像只能一个个搜索，感觉比网页版弱多了。
③代理设置好像会影响到全系统吧，感觉影响太大了。
没有考虑到的是开发者的精力和时间、以及服务器的运维成本了。

**Comment by yuyue2013** [comment]
网页版还是很不错的  感觉比应用程序好用

**Comment by decentone** [comment]
希望更新网页版，部署其实还是很方便的，对于有服务器的同学很适合

**Comment by Roger0812** [comment]
还是比较希望更新网页版的吧。方便快捷，对于我们来说，也省去了打开VPN的一步，挺快捷的。不然我打开网页版都需要打开VPN，太麻烦了。不过也辛苦作者更新了

**Comment by 97381736** [comment]
个人觉得这款软件的精髓就在于网页版，希望作者专注于网页版的更新，之前的网页版+小程序就非常的绝妙啊！

**Comment by hugoyue** [comment]
> 希望继续更新网页版，这个3.0的本地化版有点鸡肋。因为现在大家搜索磁力为了寻求方便，大多都是通过网页搞的，很少人会在本地安装一个客户端，本身太明显了，用这玩意的，大多是看片的，在电脑装个客户端，这样就尴尬了。
> 
> 其次，一大堆目标源都需要翻墙才能搜索到，网页版的话，如果在国外服务器上，可以外代一些被墙渠道，但是在本地，这就尴尬了！~
> 
> 刚体验了一下，客户端版本的，搜索太慢了，体验也很不好，比网页版差太多了，也不方便，因此，希望还是专注于网页版的开发。

同意

**Comment by xiandanin** [comment]
[electron-web](https://github.com/xiandanin/magnetW/tree/electron-web)分支

**Comment by LunaticTian** [comment]
明白作者的寒心，自己开源的作品被别人拿去魔改赚钱心里是不好受的。但其实桌面版本更加方便拿去赚钱和魔改了，所以其实没差反而更严重。

**Comment by wzsjackson** [comment]
求war包~

**Comment by xiandanin** [comment]
> 求war包~

在[releases](https://github.com/xiandanin/magnetW/releases)里啊

**Comment by doumeki** [comment]
希望能保留有网页版，毕竟哪都能用

**Comment by zhujitop** [comment]
网页版本现在还能用吗？

**Comment by keventseng** [comment]
网页版还是很方便的，因为有事在外面搜一下新片子，有的就直接在手机用aria2远程下载回家了。

**Comment by LunaticTian** [comment]
网页版怎么编译或者使用？现行代码

**Comment by xiandanin** [comment]
旧版规则会在 [https://magnetw.app/magnetw_2x.json](https://magnetw.app/magnetw_2x.json) 继续更新
现有的可以自定义配置更改到新地址，或者重新下载 [releases 2.1.4](https://github.com/xiandanin/magnetW/releases/tag/2.1.4)

旧版文档在[wiki 2.x](https://github.com/xiandanin/magnetW/wiki/2.x)

始终喜欢旧版的，可以继续使用

**Comment by jiyiv5** [comment]
搭建了网页版,如何防止别人通过api/source 获取到我的rule.json？？

**Comment by jiyiv5** [comment]
还有,想问一下网页版的如何开启搜索屏蔽功能？
