### ISSUE TITLE
Tomcat9部署报错

### ISSUE THREAD

**Issue by Abnerya** [xiandanin/magnetW#56]
Tomcat9部署War包出错
打开页面后报错{"success":false,"message":"Index: 0, Size: 0"}
[magnetw.error.log](https://github.com/xiandanin/magnetW/files/3924893/magnetw.error.log)

**Comment by xiandanin** [comment]
更新了规则，现在重新启动一下

**Comment by Abnerya** [comment]
正常了！非常感谢！
