### ISSUE TITLE
各种错哦，根本不可用啊

### ISSUE THREAD

**Issue by yudar1024** [xiandanin/magnetW#58]
523 - "<!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n<meta http-equiv=\"refresh\" content=\"0\">\n\n<title>www.zhongzihu.com | 523: Origin is unreachable</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n\n\n\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n\n \n\n <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n <div class=\"cf-wrapper cf-error-overview\">\n <h1>\n \n <span class=\"cf-error-type\">Error</span>\n <span class=\"cf-error-code\">523</span>\n <small class=\"heading-ray-id\">Ray ID: 547a057e7bc73bcd &bull; 2019-12-19 14:21:10 UTC</small>\n </h1>\n <h2 class=\"cf-subheadline\">Origin is unreachable</h2>\n </div>\n \n <div class=\"cf-section cf-highlight cf-status-display\">\n <div class=\"cf-wrapper\">\n <div class=\"cf-columns cols-3\">\n \n<div id=\"cf-browser-status\" class=\"cf-column cf-status-item cf-browser-status \">\n <div class=\"cf-icon-error-container\">\n <i class=\"cf-icon cf-icon-browser\"></i>\n <i class=\"cf-icon-status cf-icon-ok\"></i>\n </div>\n <span class=\"cf-status-desc\">You</span>\n <h3 class=\"cf-status-name\">Browser</h3>\n <span class=\"cf-status-label\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\"cf-column cf-status-item cf-cloudflare-status \">\n <div class=\"cf-icon-error-container\">\n <i class=\"cf-icon cf-icon-cloud\"></i>\n <i class=\"cf-icon-status cf-icon-ok\"></i>\n </div>\n <span class=\"cf-status-desc\">Paris</span>\n <h3 class=\"cf-status-name\">Cloudflare</h3>\n <span class=\"cf-status-label\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-column cf-status-item cf-host-status cf-error-source\">\n <div class=\"cf-icon-error-container\">\n <i class=\"cf-icon cf-icon-server\"></i>\n <i class=\"cf-icon-status cf-icon-error\"></i>\n </div>\n <span class=\"cf-status-desc\">www.zhongzihu.com</span>\n <h3 class=\"cf-status-name\">Host</h3>\n <span class=\"cf-status-

一搜索就报上面错误。3.0版本

**Comment by xiandanin** [comment]
这个站挂了  看会不会再更新吧

**Comment by qinheng053** [comment]
各种报错

**Comment by xiandanin** [comment]
@qinheng053 报什么错

**Comment by qinheng053** [comment]
ERROR:ETIMEDOUT

**Comment by xiandanin** [comment]
大部分站都被墙了 需要挂代理  [文档](#%E5%90%AF%E7%94%A8%E4%BB%A3%E7%90%86)不是写了吗
