### ISSUE TITLE
Could you please add 1337X And The Pirate Bay

### ISSUE THREAD

**Issue by Sachinart** [xiandanin/magnetW#59]
Hello,

I really love your script & work you have done. That's unbelievable thing!

Please add 1337X torrent (1337x.to) & the pirate bay, It would be really appreciated. One more thing just make this script for Tomcat as 2.14 version or add this two client in Rule.json.

Thank You!

**Comment by Sachinart** [comment]
Hello, brother!

I saw that you have added 1337x and some new clients, But please just create this script for tomcat as version 2.14. It would be really appreciated.

**You are a genius.**

Thank You!

**Comment by xiandanin** [comment]
download again [2.1.4](https://github.com/xiandanin/magnetW/releases/tag/2.1.4)

will update here https://magnetw.app/magnetw_2x.json

>1337x webpage structure is not applicable for 2.x version
