### ISSUE TITLE
希望更新

### ISSUE THREAD

**Issue by rniceplue** [xiandanin/magnetW#61]
希望更新网页版

**Comment by xiandanin** [comment]
会在 [https://magnetw.app/magnetw_2x.json](https://magnetw.app/magnetw_2x.json)更新 

[releases 2.1.4](https://github.com/xiandanin/magnetW/releases/tag/2.1.4)

文档在[wiki 2.x](https://github.com/xiandanin/magnetW/wiki/2.x)

**Comment by rniceplue** [comment]
thanks------------------ 原始邮件 ------------------
发件人: "Xian Dan"<notifications@github.com>
发送时间: 2019年12月31日(星期二) 中午1:46
收件人: "xiandanin/magnetW"<magnetW@noreply.github.com>;
抄送: "rniceplue"<1312030334@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xiandanin/magnetW] 希望更新 (#61)



会在 https://magnetw.app/magnetw_2x.json更新
 
releases 2.1.4
 
文档在wiki 2.x
 
&mdash;
