### ISSUE TITLE
地址解析

### ISSUE THREAD

**Issue by 232490026** [xiandanin/magnetW#69]
>操作系统版本：  MacOS
>应用版本：  3.1版本

#### 问题描述：
更新完3.1最新版之后，BTSOW的解析还是和之前一样有问题，复制链接之后获得的不是磁力链接而是这么一个地址
https://btos.pw/magnet/detail/hash/92313989cfe112af884527590cae4ebcfdbaee37
应该把'https://btos.pw/magnet/detail/hash/'都变成磁力头

**Comment by 232490026** [comment]
另外希望支持⌘+w的快捷键

**Comment by xiandanin** [comment]
⌘+w是什么功能的快捷键

**Comment by 232490026** [comment]
再另外，搜索栏现在也变成菜单栏的拖动效果了，搜索名字中间输入错误的话，必须全部清除掉，而不能用鼠标来框中几个字

**Comment by 232490026** [comment]
> ⌘+w是什么功能的快捷键

关闭界面而不关闭程序，这个软件重新打开加载还是有一点小卡顿的
