### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by louieaa** [xiandanin/magnetW#76]
>操作系统版本：  mac 和 win 同样报错
>应用版本：  v3.1.0

#### 问题描述：
![image](https://user-images.githubusercontent.com/42113246/71705497-07ea1f00-2e1b-11ea-8b87-d448265c809c.png)

解开了app.asar，看了一下，猜测是ip没拿到，导致传参是:::9000
![image](https://user-images.githubusercontent.com/42113246/71705584-7929d200-2e1b-11ea-93d0-f0195364f414.png)

#### 异常日志：
```

```

**Comment by xiandanin** [comment]
查一下是不是9000端口被占用了，或者已经有一个magnetW进程了

**Comment by louieaa** [comment]
@xiandanin 只打开了一个magnetW
9000端口的情况（不会看是否被占用）
![image](https://user-images.githubusercontent.com/42113246/71706088-ca3ac580-2e1d-11ea-99cf-a4f9be8a1854.png)

**Comment by xiandanin** [comment]
这是关掉应用后的调的命令吗

**Comment by louieaa** [comment]
首次打开就报错

**Comment by louieaa** [comment]
安装后打开报错的版本是3.1.0，现在也有这个问题，推测是第三方插件更新了版本，锁定koa版本试试。

**Comment by louieaa** [comment]
9000端口情况
COMMAND     PID    USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
?\x81?   35080 louiebb   47u  IPv6 0x7f4d24abdecbaf1      0t0  TCP *:cslistener (LISTEN)

**Comment by louieaa** [comment]
9000端口情况
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
?\x81? 35080 louiebb 47u IPv6 xxxxxxxxxxxxx 0t0 TCP *:cslistener (LISTEN)

**Comment by xiandanin** [comment]
把35080杀了应用卸掉，试试这个
https://dl.magnetw.app/magnetw-3.1.1-beta-mac.zip

**Comment by louieaa** [comment]
后台常驻问题，给你看看我录的视频
https://pan.baidu.com/s/1uUYcISy6qzw8vMQedojrEA

**Comment by louieaa** [comment]
不影响使用，这个issue我关了

**Comment by xiandanin** [comment]
跟 [#69](https://github.com/xiandanin/magnetW/issues/69#issuecomment-569598518) 其实是同一个问题，下版会解决

**Comment by louieaa** [comment]
好的，辛苦作者了。我是电影迷，非常感谢，工具很好用。
