### ISSUE TITLE
windows10关闭软件之后，进程还在

### ISSUE THREAD

**Issue by huanx9** [xiandanin/magnetW#89]
>操作系统版本：  
>应用版本：  

最新的版本

#### 问题描述：

windows10关闭软件之后，进程还在

#### 异常日志（上传文件到这里）：
```

```

**Comment by panghwi** [comment]
Win7x64系统下同样，而且任务管理器中大约有4-5个同样的进程，需要一个个关掉。

**Comment by coslyk** [comment]
Debian 10同样的问题，希望作者修复一下。

**Comment by kyouetuhon** [comment]
俺也一样

**Comment by shantelwells** [comment]
Fuck you
